### ISSUE TITLE
Can punctuation handling be configurable via a parameter for type "reading"?

### ISSUE THREAD

**Issue by jdimeo** [surveycto/timed-grid-test#72]
I was surprised that punctuation is forced to be a separate word. Can we toggle this behavior with a parameter?
It seems like it would be easier on the data collector to not have to think about which buttons are clickable and which aren't (and to have fewer overall on the screen). I would like this configuration to work:
![image](https://user-images.githubusercontent.com/1071438/158937686-29edc51e-5d6f-414d-98e4-3eaa91197af1.png)

**Comment by mofya1** [comment]
Hi @jdimeo,

Thanks for taking time to test out this field plug-in. Unfortunately there is no _parameter_ to manage how punctuation marks appear. The current design was a deliberate one based on feedback from some EGRA implementers. There is school of thought where the punctuation mark combined with the word can be confusing for the user. 

The implementation is really a starting point and you are welcome to modify it as needed using the steps which you find in our [guide to creating field plug-ins](https://support.surveycto.com/hc/en-us/articles/360052426933-Guide-to-creating-field-plug-ins).

If you have further questions, and you are a paid and trial user of SurveyCTO, you can [submit a support request](https://support.surveycto.com/hc/en-us/requests/new) for fast, professional, 24/7 support. Otherwise, you can post to the [user forums](https://support.surveycto.com/hc/en-us/community/topics/200604277-Advice-hacks-and-questions-about-using-SurveyCTO).

Thanks!

**Comment by jdimeo** [comment]
Right - since this is for data collectors, not children, having it be a parameter means we can test both ways with our particular data collectors and go with the one that makes the most sense to them. I am a paying customer, yes, but wanted to log this feature request here for better visibility.

**Comment by TheOmnimax** [comment]
Hi @jdimeo,

If you have a suggestion on a way to improve SurveyCTO, including how to improve a field plug-in developed by SurveyCTO, you can submit a feature request. Check out our support article on [how to submit a feature request.](https://support.surveycto.com/hc/en-us/articles/360036824753-How-to-submit-a-feature-request) to learn more. We keep a much closer eye on support requests and feature requests than we do on GitHub, so those are the best places to ask for help or request new features. Thanks!
